name: Feature request
description: Suggest something new
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What do you want to do?
      description: The task you're trying to get done, rather than the feature you have in mind.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: How could tgju-rates help?
